import matplotlib.pyplot as plt
import networkx as nx
G=nx.DiGraph()
G.add_node("a")
G.add_node("b")
G.add_node("c")
G.add_node("d")
G.add_node("e")
G.add_node("f")
G.add_node("g")
G.add_node("h")
G.add_node("i")
G.add_node("j")
G.add_node("k")
G.add_node("l")
G.add_node("m")
G.add_node("n")
G.add_node("o")
G.add_node("p")
G.add_node("q")
G.add_node("r")
G.add_node("s")
G.add_node("t")
G.add_node("u")
G.add_node("v")
G.add_node("w")
G.add_node("x")
G.add_node("y")
G.add_node("z")
G.add_edge("a", "z")
G.add_edge("a", "y")
G.add_edge("a", "u")
G.add_edge("a", "t")
G.add_edge("a", "q")
G.add_edge("a", "m")
G.add_edge("a", "j")
G.add_edge("a", "i")
G.add_edge("a", "h")
G.add_edge("a", "d")
G.add_edge("b", "z")
G.add_edge("b", "v")
G.add_edge("b", "u")
G.add_edge("b", "p")
G.add_edge("b", "o")
G.add_edge("b", "n")
G.add_edge("b", "m")
G.add_edge("b", "j")
G.add_edge("b", "i")
G.add_edge("b", "d")
G.add_edge("c", "z")
G.add_edge("c", "x")
G.add_edge("c", "v")
G.add_edge("c", "t")
G.add_edge("c", "q")
G.add_edge("c", "p")
G.add_edge("c", "k")
G.add_edge("c", "j")
G.add_edge("c", "h")
G.add_edge("c", "f")
G.add_edge("d", "y")
G.add_edge("d", "w")
G.add_edge("d", "p")
G.add_edge("d", "o")
G.add_edge("d", "n")
G.add_edge("d", "j")
G.add_edge("d", "h")
G.add_edge("d", "g")
G.add_edge("d", "b")
G.add_edge("d", "a")
G.add_edge("e", "y")
G.add_edge("e", "w")
G.add_edge("e", "t")
G.add_edge("e", "r")
G.add_edge("e", "p")
G.add_edge("e", "o")
G.add_edge("e", "n")
G.add_edge("e", "m")
G.add_edge("e", "h")
G.add_edge("e", "f")
G.add_edge("f", "x")
G.add_edge("f", "w")
G.add_edge("f", "t")
G.add_edge("f", "r")
G.add_edge("f", "o")
G.add_edge("f", "m")
G.add_edge("f", "l")
G.add_edge("f", "g")
G.add_edge("f", "e")
G.add_edge("f", "c")
G.add_edge("g", "y")
G.add_edge("g", "x")
G.add_edge("g", "v")
G.add_edge("g", "n")
G.add_edge("g", "m")
G.add_edge("g", "j")
G.add_edge("g", "i")
G.add_edge("g", "h")
G.add_edge("g", "f")
G.add_edge("g", "d")
G.add_edge("h", "z")
G.add_edge("h", "y")
G.add_edge("h", "x")
G.add_edge("h", "u")
G.add_edge("h", "j")
G.add_edge("h", "g")
G.add_edge("h", "e")
G.add_edge("h", "d")
G.add_edge("h", "c")
G.add_edge("h", "a")
G.add_edge("i", "y")
G.add_edge("i", "q")
G.add_edge("i", "p")
G.add_edge("i", "o")
G.add_edge("i", "m")
G.add_edge("i", "l")
G.add_edge("i", "k")
G.add_edge("i", "g")
G.add_edge("i", "b")
G.add_edge("i", "a")
G.add_edge("j", "z")
G.add_edge("j", "s")
G.add_edge("j", "q")
G.add_edge("j", "m")
G.add_edge("j", "h")
G.add_edge("j", "g")
G.add_edge("j", "d")
G.add_edge("j", "c")
G.add_edge("j", "b")
G.add_edge("j", "a")
G.add_edge("k", "y")
G.add_edge("k", "x")
G.add_edge("k", "w")
G.add_edge("k", "v")
G.add_edge("k", "s")
G.add_edge("k", "p")
G.add_edge("k", "o")
G.add_edge("k", "l")
G.add_edge("k", "i")
G.add_edge("k", "c")
G.add_edge("l", "z")
G.add_edge("l", "y")
G.add_edge("l", "v")
G.add_edge("l", "u")
G.add_edge("l", "s")
G.add_edge("l", "n")
G.add_edge("l", "m")
G.add_edge("l", "k")
G.add_edge("l", "i")
G.add_edge("l", "f")
G.add_edge("m", "v")
G.add_edge("m", "p")
G.add_edge("m", "l")
G.add_edge("m", "j")
G.add_edge("m", "i")
G.add_edge("m", "g")
G.add_edge("m", "f")
G.add_edge("m", "e")
G.add_edge("m", "b")
G.add_edge("m", "a")
G.add_edge("n", "y")
G.add_edge("n", "w")
G.add_edge("n", "u")
G.add_edge("n", "s")
G.add_edge("n", "p")
G.add_edge("n", "l")
G.add_edge("n", "g")
G.add_edge("n", "e")
G.add_edge("n", "d")
G.add_edge("n", "b")
G.add_edge("o", "y")
G.add_edge("o", "v")
G.add_edge("o", "u")
G.add_edge("o", "t")
G.add_edge("o", "k")
G.add_edge("o", "i")
G.add_edge("o", "f")
G.add_edge("o", "e")
G.add_edge("o", "d")
G.add_edge("o", "b")
G.add_edge("p", "w")
G.add_edge("p", "u")
G.add_edge("p", "n")
G.add_edge("p", "m")
G.add_edge("p", "k")
G.add_edge("p", "i")
G.add_edge("p", "e")
G.add_edge("p", "d")
G.add_edge("p", "c")
G.add_edge("p", "b")
G.add_edge("q", "z")
G.add_edge("q", "x")
G.add_edge("q", "v")
G.add_edge("q", "u")
G.add_edge("q", "t")
G.add_edge("q", "r")
G.add_edge("q", "j")
G.add_edge("q", "i")
G.add_edge("q", "c")
G.add_edge("q", "a")
G.add_edge("r", "z")
G.add_edge("r", "x")
G.add_edge("r", "w")
G.add_edge("r", "v")
G.add_edge("r", "u")
G.add_edge("r", "t")
G.add_edge("r", "s")
G.add_edge("r", "q")
G.add_edge("r", "f")
G.add_edge("r", "e")
G.add_edge("s", "z")
G.add_edge("s", "x")
G.add_edge("s", "w")
G.add_edge("s", "v")
G.add_edge("s", "u")
G.add_edge("s", "r")
G.add_edge("s", "n")
G.add_edge("s", "l")
G.add_edge("s", "k")
G.add_edge("s", "j")
G.add_edge("t", "z")
G.add_edge("t", "x")
G.add_edge("t", "w")
G.add_edge("t", "r")
G.add_edge("t", "q")
G.add_edge("t", "o")
G.add_edge("t", "f")
G.add_edge("t", "e")
G.add_edge("t", "c")
G.add_edge("t", "a")
G.add_edge("u", "s")
G.add_edge("u", "r")
G.add_edge("u", "q")
G.add_edge("u", "p")
G.add_edge("u", "o")
G.add_edge("u", "n")
G.add_edge("u", "l")
G.add_edge("u", "h")
G.add_edge("u", "b")
G.add_edge("u", "a")
G.add_edge("v", "s")
G.add_edge("v", "r")
G.add_edge("v", "q")
G.add_edge("v", "o")
G.add_edge("v", "m")
G.add_edge("v", "l")
G.add_edge("v", "k")
G.add_edge("v", "g")
G.add_edge("v", "c")
G.add_edge("v", "b")
G.add_edge("w", "x")
G.add_edge("w", "t")
G.add_edge("w", "s")
G.add_edge("w", "r")
G.add_edge("w", "p")
G.add_edge("w", "n")
G.add_edge("w", "k")
G.add_edge("w", "f")
G.add_edge("w", "e")
G.add_edge("w", "d")
G.add_edge("x", "w")
G.add_edge("x", "t")
G.add_edge("x", "s")
G.add_edge("x", "r")
G.add_edge("x", "q")
G.add_edge("x", "k")
G.add_edge("x", "h")
G.add_edge("x", "g")
G.add_edge("x", "f")
G.add_edge("x", "c")
G.add_edge("y", "o")
G.add_edge("y", "n")
G.add_edge("y", "l")
G.add_edge("y", "k")
G.add_edge("y", "i")
G.add_edge("y", "h")
G.add_edge("y", "g")
G.add_edge("y", "e")
G.add_edge("y", "d")
G.add_edge("y", "a")
G.add_edge("z", "t")
G.add_edge("z", "s")
G.add_edge("z", "r")
G.add_edge("z", "q")
G.add_edge("z", "l")
G.add_edge("z", "j")
G.add_edge("z", "h")
G.add_edge("z", "c")
G.add_edge("z", "b")
G.add_edge("z", "a")
layout = nx.circular_layout(G)
nx.draw_networkx(G, pos=layout, with_labels=True)
plt.show()
