import matplotlib.pyplot as plt
import networkx as nx
G=nx.DiGraph()
G.add_node("a")
G.add_node("b")
G.add_node("c")
G.add_node("d")
G.add_node("e")
G.add_node("f")
G.add_node("g")
G.add_node("h")
G.add_node("i")
G.add_node("j")
G.add_node("k")
G.add_node("l")
G.add_node("m")
G.add_node("n")
G.add_node("o")
G.add_node("p")
G.add_node("q")
G.add_node("r")
G.add_node("s")
G.add_node("t")
G.add_node("u")
G.add_node("v")
G.add_node("w")
G.add_node("x")
G.add_node("y")
G.add_node("z")
G.add_edge("a", "z")
G.add_edge("a", "v")
G.add_edge("a", "t")
G.add_edge("a", "r")
G.add_edge("a", "o")
G.add_edge("a", "j")
G.add_edge("a", "i")
G.add_edge("a", "h")
G.add_edge("a", "g")
G.add_edge("a", "c")
G.add_edge("b", "z")
G.add_edge("b", "y")
G.add_edge("b", "w")
G.add_edge("b", "t")
G.add_edge("b", "s")
G.add_edge("b", "r")
G.add_edge("b", "l")
G.add_edge("b", "k")
G.add_edge("b", "f")
G.add_edge("b", "c")
G.add_edge("c", "y")
G.add_edge("c", "w")
G.add_edge("c", "r")
G.add_edge("c", "q")
G.add_edge("c", "o")
G.add_edge("c", "l")
G.add_edge("c", "k")
G.add_edge("c", "h")
G.add_edge("c", "b")
G.add_edge("c", "a")
G.add_edge("d", "z")
G.add_edge("d", "x")
G.add_edge("d", "v")
G.add_edge("d", "s")
G.add_edge("d", "r")
G.add_edge("d", "m")
G.add_edge("d", "j")
G.add_edge("d", "i")
G.add_edge("d", "g")
G.add_edge("d", "e")
G.add_edge("e", "y")
G.add_edge("e", "x")
G.add_edge("e", "u")
G.add_edge("e", "t")
G.add_edge("e", "p")
G.add_edge("e", "o")
G.add_edge("e", "m")
G.add_edge("e", "h")
G.add_edge("e", "g")
G.add_edge("e", "d")
G.add_edge("f", "z")
G.add_edge("f", "x")
G.add_edge("f", "w")
G.add_edge("f", "v")
G.add_edge("f", "u")
G.add_edge("f", "t")
G.add_edge("f", "l")
G.add_edge("f", "k")
G.add_edge("f", "i")
G.add_edge("f", "b")
G.add_edge("g", "w")
G.add_edge("g", "u")
G.add_edge("g", "p")
G.add_edge("g", "m")
G.add_edge("g", "k")
G.add_edge("g", "j")
G.add_edge("g", "i")
G.add_edge("g", "e")
G.add_edge("g", "d")
G.add_edge("g", "a")
G.add_edge("h", "w")
G.add_edge("h", "v")
G.add_edge("h", "u")
G.add_edge("h", "p")
G.add_edge("h", "l")
G.add_edge("h", "k")
G.add_edge("h", "i")
G.add_edge("h", "e")
G.add_edge("h", "c")
G.add_edge("h", "a")
G.add_edge("i", "z")
G.add_edge("i", "y")
G.add_edge("i", "s")
G.add_edge("i", "p")
G.add_edge("i", "o")
G.add_edge("i", "h")
G.add_edge("i", "g")
G.add_edge("i", "f")
G.add_edge("i", "d")
G.add_edge("i", "a")
G.add_edge("j", "z")
G.add_edge("j", "x")
G.add_edge("j", "s")
G.add_edge("j", "r")
G.add_edge("j", "o")
G.add_edge("j", "m")
G.add_edge("j", "l")
G.add_edge("j", "g")
G.add_edge("j", "d")
G.add_edge("j", "a")
G.add_edge("k", "z")
G.add_edge("k", "u")
G.add_edge("k", "n")
G.add_edge("k", "m")
G.add_edge("k", "l")
G.add_edge("k", "h")
G.add_edge("k", "g")
G.add_edge("k", "f")
G.add_edge("k", "c")
G.add_edge("k", "b")
G.add_edge("l", "z")
G.add_edge("l", "u")
G.add_edge("l", "s")
G.add_edge("l", "m")
G.add_edge("l", "k")
G.add_edge("l", "j")
G.add_edge("l", "h")
G.add_edge("l", "f")
G.add_edge("l", "c")
G.add_edge("l", "b")
G.add_edge("m", "z")
G.add_edge("m", "y")
G.add_edge("m", "u")
G.add_edge("m", "p")
G.add_edge("m", "l")
G.add_edge("m", "k")
G.add_edge("m", "j")
G.add_edge("m", "g")
G.add_edge("m", "e")
G.add_edge("m", "d")
G.add_edge("n", "y")
G.add_edge("n", "x")
G.add_edge("n", "w")
G.add_edge("n", "v")
G.add_edge("n", "u")
G.add_edge("n", "t")
G.add_edge("n", "q")
G.add_edge("n", "p")
G.add_edge("n", "o")
G.add_edge("n", "k")
G.add_edge("o", "z")
G.add_edge("o", "y")
G.add_edge("o", "t")
G.add_edge("o", "s")
G.add_edge("o", "n")
G.add_edge("o", "j")
G.add_edge("o", "i")
G.add_edge("o", "e")
G.add_edge("o", "c")
G.add_edge("o", "a")
G.add_edge("p", "y")
G.add_edge("p", "x")
G.add_edge("p", "s")
G.add_edge("p", "q")
G.add_edge("p", "n")
G.add_edge("p", "m")
G.add_edge("p", "i")
G.add_edge("p", "h")
G.add_edge("p", "g")
G.add_edge("p", "e")
G.add_edge("q", "y")
G.add_edge("q", "x")
G.add_edge("q", "w")
G.add_edge("q", "v")
G.add_edge("q", "u")
G.add_edge("q", "t")
G.add_edge("q", "r")
G.add_edge("q", "p")
G.add_edge("q", "n")
G.add_edge("q", "c")
G.add_edge("r", "x")
G.add_edge("r", "w")
G.add_edge("r", "v")
G.add_edge("r", "t")
G.add_edge("r", "q")
G.add_edge("r", "j")
G.add_edge("r", "d")
G.add_edge("r", "c")
G.add_edge("r", "b")
G.add_edge("r", "a")
G.add_edge("s", "x")
G.add_edge("s", "w")
G.add_edge("s", "t")
G.add_edge("s", "p")
G.add_edge("s", "o")
G.add_edge("s", "l")
G.add_edge("s", "j")
G.add_edge("s", "i")
G.add_edge("s", "d")
G.add_edge("s", "b")
G.add_edge("t", "y")
G.add_edge("t", "s")
G.add_edge("t", "r")
G.add_edge("t", "q")
G.add_edge("t", "o")
G.add_edge("t", "n")
G.add_edge("t", "f")
G.add_edge("t", "e")
G.add_edge("t", "b")
G.add_edge("t", "a")
G.add_edge("u", "v")
G.add_edge("u", "q")
G.add_edge("u", "n")
G.add_edge("u", "m")
G.add_edge("u", "l")
G.add_edge("u", "k")
G.add_edge("u", "h")
G.add_edge("u", "g")
G.add_edge("u", "f")
G.add_edge("u", "e")
G.add_edge("v", "x")
G.add_edge("v", "w")
G.add_edge("v", "u")
G.add_edge("v", "r")
G.add_edge("v", "q")
G.add_edge("v", "n")
G.add_edge("v", "h")
G.add_edge("v", "f")
G.add_edge("v", "d")
G.add_edge("v", "a")
G.add_edge("w", "v")
G.add_edge("w", "s")
G.add_edge("w", "r")
G.add_edge("w", "q")
G.add_edge("w", "n")
G.add_edge("w", "h")
G.add_edge("w", "g")
G.add_edge("w", "f")
G.add_edge("w", "c")
G.add_edge("w", "b")
G.add_edge("x", "v")
G.add_edge("x", "s")
G.add_edge("x", "r")
G.add_edge("x", "q")
G.add_edge("x", "p")
G.add_edge("x", "n")
G.add_edge("x", "j")
G.add_edge("x", "f")
G.add_edge("x", "e")
G.add_edge("x", "d")
G.add_edge("y", "t")
G.add_edge("y", "q")
G.add_edge("y", "p")
G.add_edge("y", "o")
G.add_edge("y", "n")
G.add_edge("y", "m")
G.add_edge("y", "i")
G.add_edge("y", "e")
G.add_edge("y", "c")
G.add_edge("y", "b")
G.add_edge("z", "o")
G.add_edge("z", "m")
G.add_edge("z", "l")
G.add_edge("z", "k")
G.add_edge("z", "j")
G.add_edge("z", "i")
G.add_edge("z", "f")
G.add_edge("z", "d")
G.add_edge("z", "b")
G.add_edge("z", "a")
layout = nx.circular_layout(G)
nx.draw_networkx(G, pos=layout, with_labels=True)
plt.show()
